### ISSUE TITLE
Performance reports don't work

### ISSUE THREAD

**Issue by radiusmk** [Secure-Compliance-Solutions-LLC/GVM-Docker#148]
**Describe the bug**
In Administration > Performance options any information is showed.

**To Reproduce**
1. Go to "Administration > Performance
2. Choose any data and click on "Update"
3. See the problem.

**Screenshots**
![image](https://user-images.githubusercontent.com/47662720/113005713-183a9800-914b-11eb-9f42-ded533423d3a.png)

**Comment by austinsonger** [comment]
What result are you getting?

**Comment by radiusmk** [comment]
> 
> 
> What result are you getting?

No results are displayed. Do I need to install or configure anything? 

![image](https://user-images.githubusercontent.com/47662720/117876872-3c28e780-b27a-11eb-8d9e-58c90a7c66cd.png)

**Comment by austinsonger** [comment]
Do you have the latest version deployed


In `postgresql.conf`, the following should be uncommented
- https://community.greenbone.net/t/everything-works-but-i-cant-see-any-report/5875/12
```
# jit = off 
```

```
jit = off 
```

- https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker/commit/18bdeee5341d44188eb1e1232f736174bef39a08

Which we already fixed. So This is something that we will need to see if others are running into this issue, because we are not running into this issue on our side.

**Comment by radiusmk** [comment]
I updated docker image right now, and the"postgresql.conf" file came without uncommented "jit=off".

![image](https://user-images.githubusercontent.com/47662720/118026725-845a0f80-b337-11eb-8944-c1e3df8a2bac.png)

**Comment by austinsonger** [comment]
Yes in the comment above I added when we fixed this issue. I'm unable to reproduce this.

What is your host device information:
OS: 
Version:

**Comment by grantemsley** [comment]
I'm seeing pretty much the same thing, except I don't even see the "Report for GMP scanner" box.

![image](https://user-images.githubusercontent.com/669579/119999036-4b5ca480-bf9f-11eb-898f-65625a0afecc.png)

Running the docker image securecompliance/gvm (latest as of today) on a Ubuntu 20.04 host machine, freshly installed with no existing data.

I'm happy to help if there's more details I can provide or things I can try!

**Comment by grantemsley** [comment]
Pretty sure I figured out why the performance reports don't work.

From their INSTALL.MD file:
> Prerequisites for generating system reports:
> A program in the PATH, with usage gvmcg seconds type, where seconds is the number of seconds before now that the report covers, and type is the type of report. When called with type titles the script must print a list of possible types, where the name of the type is everything up to the first space and everything else is a title for the report. When called with one of these types, gvmcg must print a PNG in base64 encoding. When called with the special type blank, gvmcg must print a PNG in base64 for the Manager to use when a request for one of the titled types fails. gvmcg may indicate failure by simply refraining from printing.

So it has [collectd](https://collectd.org/) or some similar daemon running collecting system stats and a custom script to pull the graphs out of it.  Since I can't find code for gvmcg, just a few references to it, I'm assuming they aren't sharing that in the open source version. To get performance graphs, you'd have to have your own daemon collecting the stats you want to show, and a script that generates png graphics from that data.

Makes sense to do on a dedicated appliance, but when running it inside docker containers, probably not worth the effort and performance hit of collecting and integrating that into the container. If you need system stats, best to collect them on the host.

So, looks like its not a problem with the docker container, and not something that can easily be added.
