### ISSUE TITLE
[Bug] admin password is always reset to defautl admin at each reboot docker

### ISSUE THREAD

**Issue by netbix** [Secure-Compliance-Solutions-LLC/GVM-Docker#192]
At each reboot the password of the admin user is always reset by the env file. Even after changing the password via the web it is always reset

**To Reproduce**

docker-compose pull
docker-compose rm
docker-compore up -d

this is my compose:

version: '3.4'
services:
  gvmgsa:
    image: securecompliance/gvm
    hostname: gvmgsa
    container_name: gvmgsa
    restart: always
    ports:
      - "8082:9392"
      - "5432:5432"
      - "2222:22"
    env_file:
      - ./config/local.env
    volumes:
      - gvmgsa_data:/data

volumes:
  gvmgsa_data:
    name: gvmgsa_data

**Comment by austinsonger** [comment]
@grantemsley it looks like this could be related to the docker compose file. Any thoughts?

**Comment by grantemsley** [comment]
It's from setting the USERNAME and PASSWORD environment variables.  Doesn't matter if you set that through docker compose or --env command line, it always sets the password on startup, overwriting whatever was there before.

https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker/blob/e97bf80775404c03a1af8f49ce02c4fef4ff0b59/scripts/start.sh#L305

This is actually GOOD behaviour in my opinion, and the way I've seen many docker containers operate - the environment variables always take priority, otherwise the PASSWORD variable doesn't do anything in future runs. 

Set the password you want in your local.env file.

**Comment by netbix** [comment]
before the version 20.8.1 will not be like this, after the password change via web it remains. I usually distribute the password with the variables for the first installation, later I prefer to customize it

**Comment by grantemsley** [comment]
To change the behavior to have the environment variable only set the initial password, the line I linked above could be moved to inside one of the firstrun blocks.  Probably inside the one that only runs on initial install for a new data folder.

Up to the devs here on which method they prefer.  Either way should add it to the documentation that the environment variable either resets the password on every start up, or only works for the initial setup.

**Comment by austinsonger** [comment]
@pixelsquared  What you?

**Comment by mrod23** [comment]
@netbix  why are you resetting the Docker container? Why not just delete it and create a new one
