### ISSUE TITLE
Folder /usr/local/share/gvm/gvmd/report_formats/ doesn't exist.

### ISSUE THREAD

**Issue by AjaCoder** [Secure-Compliance-Solutions-LLC/GVM-Docker#90]
**Describe the bug**
After building and running the image, as a base of another image, the folder /usr/local/share/gvm/gvmd/report_formats/ is not present on the container.
I found the bug after a task I was running didn't finish, reached the high 90% but didn't finish (After more then 24 hours). When investigating the issue I saw in the logs the errors about report_formats not found, not sure if it's related but this is how I found the issue.

**To Reproduce**
1. Build image(As base of another image)
2. Start the container(I run the start.sh script).
3. Open bash and check if the folder exists.

**Additional context**
Using latest - 'FROM securecompliance/gvm:latest'
The dashboard is working and so is creating targets, tasks, starting tasks, and syncing.

Appreciate the help.

**Comment by pixelsquared** [comment]
This looks like a bug in the start.sh script. It does not copy the report_formats folder to the data folder when setting up the /usr/local/share/gvm/gvmd folder to symlink to the /data folder.

**Comment by AjaCoder** [comment]
I can confirm that the fix is working, the directory is present now.

**Comment by NimaSaed** [comment]
This issue is not solve, line 126 is causing it, since `/usr/local/share/gvm/gvmd/report_formats` does not exist.

https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker/blob/3b79981e1229011cef157303b2c98e3c0782e475/scripts/start.sh#L124-L129

You do not need  "Fixing report formats" part, because you are going to remove `/usr/local/var/lib/gvm/gvmd` in line 139 and create a link from `/data/gvmd`

https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker/blob/3b79981e1229011cef157303b2c98e3c0782e475/scripts/start.sh#L136-L145

So just remove 124 to 129, unless I am missing something else.

**Comment by AjaCoder** [comment]
@NimaSaed You are correct, last night I did some test and indeed the issue still exists, at least when using as a base image.

**Comment by NimaSaed** [comment]
I have tested this and it is working.

#95
